apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: andersbuskdemoapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: andersbuskdemoapp 
    spec:
      containers:
        - name: andersbuskdemoapp 
          image: compulsoryassignmentacr.azurecr.io/andersbuskdemoapp
          ports:
          - containerPort: 80